-- Alter Admins Table to add profile fields
ALTER TABLE admins ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS github_url VARCHAR(500);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(500);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS portfolio_title VARCHAR(255);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS profile_image VARCHAR(500);
